# CMake generated Testfile for 
# Source directory: /home/runner/work/ezLibs/ezLibs/Tests/TestFile
# Build directory: /home/runner/work/ezLibs/ezLibs/_codeql_build_dir/Tests/TestFile
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(TestEzBmp_Writer "/home/runner/work/ezLibs/ezLibs/_codeql_build_dir/Tests/TestFile/EzLibs_TestFile" "TestEzBmp_Writer")
set_tests_properties(TestEzBmp_Writer PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ezLibs/ezLibs/Tests/CMakeLists.txt;41;add_test;/home/runner/work/ezLibs/ezLibs/Tests/TestFile/CMakeLists.txt;53;AddTest;/home/runner/work/ezLibs/ezLibs/Tests/TestFile/CMakeLists.txt;0;")
add_test(TestEzFile_saveStringToFile "/home/runner/work/ezLibs/ezLibs/_codeql_build_dir/Tests/TestFile/EzLibs_TestFile" "TestEzFile_saveStringToFile")
set_tests_properties(TestEzFile_saveStringToFile PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ezLibs/ezLibs/Tests/CMakeLists.txt;41;add_test;/home/runner/work/ezLibs/ezLibs/Tests/TestFile/CMakeLists.txt;59;AddTest;/home/runner/work/ezLibs/ezLibs/Tests/TestFile/CMakeLists.txt;0;")
add_test(TestEzFile_saveBinToFile "/home/runner/work/ezLibs/ezLibs/_codeql_build_dir/Tests/TestFile/EzLibs_TestFile" "TestEzFile_saveBinToFile")
set_tests_properties(TestEzFile_saveBinToFile PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ezLibs/ezLibs/Tests/CMakeLists.txt;41;add_test;/home/runner/work/ezLibs/ezLibs/Tests/TestFile/CMakeLists.txt;60;AddTest;/home/runner/work/ezLibs/ezLibs/Tests/TestFile/CMakeLists.txt;0;")
add_test(TestEzFile_parsePathFileName "/home/runner/work/ezLibs/ezLibs/_codeql_build_dir/Tests/TestFile/EzLibs_TestFile" "TestEzFile_parsePathFileName")
set_tests_properties(TestEzFile_parsePathFileName PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ezLibs/ezLibs/Tests/CMakeLists.txt;41;add_test;/home/runner/work/ezLibs/ezLibs/Tests/TestFile/CMakeLists.txt;61;AddTest;/home/runner/work/ezLibs/ezLibs/Tests/TestFile/CMakeLists.txt;0;")
add_test(TestEzFile_simplifyFilePath "/home/runner/work/ezLibs/ezLibs/_codeql_build_dir/Tests/TestFile/EzLibs_TestFile" "TestEzFile_simplifyFilePath")
set_tests_properties(TestEzFile_simplifyFilePath PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ezLibs/ezLibs/Tests/CMakeLists.txt;41;add_test;/home/runner/work/ezLibs/ezLibs/Tests/TestFile/CMakeLists.txt;62;AddTest;/home/runner/work/ezLibs/ezLibs/Tests/TestFile/CMakeLists.txt;0;")
add_test(TestEzFile_composePath "/home/runner/work/ezLibs/ezLibs/_codeql_build_dir/Tests/TestFile/EzLibs_TestFile" "TestEzFile_composePath")
set_tests_properties(TestEzFile_composePath PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ezLibs/ezLibs/Tests/CMakeLists.txt;41;add_test;/home/runner/work/ezLibs/ezLibs/Tests/TestFile/CMakeLists.txt;63;AddTest;/home/runner/work/ezLibs/ezLibs/Tests/TestFile/CMakeLists.txt;0;")
add_test(TestEzFile_correctSlashTypeForFilePathName "/home/runner/work/ezLibs/ezLibs/_codeql_build_dir/Tests/TestFile/EzLibs_TestFile" "TestEzFile_correctSlashTypeForFilePathName")
set_tests_properties(TestEzFile_correctSlashTypeForFilePathName PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ezLibs/ezLibs/Tests/CMakeLists.txt;41;add_test;/home/runner/work/ezLibs/ezLibs/Tests/TestFile/CMakeLists.txt;64;AddTest;/home/runner/work/ezLibs/ezLibs/Tests/TestFile/CMakeLists.txt;0;")
add_test(TestEzFile_createDirectoryIfNotExist "/home/runner/work/ezLibs/ezLibs/_codeql_build_dir/Tests/TestFile/EzLibs_TestFile" "TestEzFile_createDirectoryIfNotExist")
set_tests_properties(TestEzFile_createDirectoryIfNotExist PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ezLibs/ezLibs/Tests/CMakeLists.txt;41;add_test;/home/runner/work/ezLibs/ezLibs/Tests/TestFile/CMakeLists.txt;65;AddTest;/home/runner/work/ezLibs/ezLibs/Tests/TestFile/CMakeLists.txt;0;")
add_test(TestEzBinBuf_WriteReadValueLE "/home/runner/work/ezLibs/ezLibs/_codeql_build_dir/Tests/TestFile/EzLibs_TestFile" "TestEzBinBuf_WriteReadValueLE")
set_tests_properties(TestEzBinBuf_WriteReadValueLE PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ezLibs/ezLibs/Tests/CMakeLists.txt;41;add_test;/home/runner/work/ezLibs/ezLibs/Tests/TestFile/CMakeLists.txt;71;AddTest;/home/runner/work/ezLibs/ezLibs/Tests/TestFile/CMakeLists.txt;0;")
add_test(TestEzBinBuf_WriteReadValueBE "/home/runner/work/ezLibs/ezLibs/_codeql_build_dir/Tests/TestFile/EzLibs_TestFile" "TestEzBinBuf_WriteReadValueBE")
set_tests_properties(TestEzBinBuf_WriteReadValueBE PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ezLibs/ezLibs/Tests/CMakeLists.txt;41;add_test;/home/runner/work/ezLibs/ezLibs/Tests/TestFile/CMakeLists.txt;72;AddTest;/home/runner/work/ezLibs/ezLibs/Tests/TestFile/CMakeLists.txt;0;")
add_test(TestEzBinBuf_WriteReadArrayLE "/home/runner/work/ezLibs/ezLibs/_codeql_build_dir/Tests/TestFile/EzLibs_TestFile" "TestEzBinBuf_WriteReadArrayLE")
set_tests_properties(TestEzBinBuf_WriteReadArrayLE PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ezLibs/ezLibs/Tests/CMakeLists.txt;41;add_test;/home/runner/work/ezLibs/ezLibs/Tests/TestFile/CMakeLists.txt;73;AddTest;/home/runner/work/ezLibs/ezLibs/Tests/TestFile/CMakeLists.txt;0;")
add_test(TestEzBinBuf_WriteReadArrayBE "/home/runner/work/ezLibs/ezLibs/_codeql_build_dir/Tests/TestFile/EzLibs_TestFile" "TestEzBinBuf_WriteReadArrayBE")
set_tests_properties(TestEzBinBuf_WriteReadArrayBE PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ezLibs/ezLibs/Tests/CMakeLists.txt;41;add_test;/home/runner/work/ezLibs/ezLibs/Tests/TestFile/CMakeLists.txt;74;AddTest;/home/runner/work/ezLibs/ezLibs/Tests/TestFile/CMakeLists.txt;0;")
add_test(TestEzBinBuf_SetDatasGetDatas "/home/runner/work/ezLibs/ezLibs/_codeql_build_dir/Tests/TestFile/EzLibs_TestFile" "TestEzBinBuf_SetDatasGetDatas")
set_tests_properties(TestEzBinBuf_SetDatasGetDatas PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ezLibs/ezLibs/Tests/CMakeLists.txt;41;add_test;/home/runner/work/ezLibs/ezLibs/Tests/TestFile/CMakeLists.txt;75;AddTest;/home/runner/work/ezLibs/ezLibs/Tests/TestFile/CMakeLists.txt;0;")
add_test(TestEzBinBuf_ClearSize "/home/runner/work/ezLibs/ezLibs/_codeql_build_dir/Tests/TestFile/EzLibs_TestFile" "TestEzBinBuf_ClearSize")
set_tests_properties(TestEzBinBuf_ClearSize PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ezLibs/ezLibs/Tests/CMakeLists.txt;41;add_test;/home/runner/work/ezLibs/ezLibs/Tests/TestFile/CMakeLists.txt;76;AddTest;/home/runner/work/ezLibs/ezLibs/Tests/TestFile/CMakeLists.txt;0;")
add_test(TestEzBinBuf_Reserve "/home/runner/work/ezLibs/ezLibs/_codeql_build_dir/Tests/TestFile/EzLibs_TestFile" "TestEzBinBuf_Reserve")
set_tests_properties(TestEzBinBuf_Reserve PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ezLibs/ezLibs/Tests/CMakeLists.txt;41;add_test;/home/runner/work/ezLibs/ezLibs/Tests/TestFile/CMakeLists.txt;77;AddTest;/home/runner/work/ezLibs/ezLibs/Tests/TestFile/CMakeLists.txt;0;")
add_test(TestEzBinBuf_OperatorAt "/home/runner/work/ezLibs/ezLibs/_codeql_build_dir/Tests/TestFile/EzLibs_TestFile" "TestEzBinBuf_OperatorAt")
set_tests_properties(TestEzBinBuf_OperatorAt PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ezLibs/ezLibs/Tests/CMakeLists.txt;41;add_test;/home/runner/work/ezLibs/ezLibs/Tests/TestFile/CMakeLists.txt;78;AddTest;/home/runner/work/ezLibs/ezLibs/Tests/TestFile/CMakeLists.txt;0;")
add_test(TestEzBinBuf_OutOfRange "/home/runner/work/ezLibs/ezLibs/_codeql_build_dir/Tests/TestFile/EzLibs_TestFile" "TestEzBinBuf_OutOfRange")
set_tests_properties(TestEzBinBuf_OutOfRange PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ezLibs/ezLibs/Tests/CMakeLists.txt;41;add_test;/home/runner/work/ezLibs/ezLibs/Tests/TestFile/CMakeLists.txt;79;AddTest;/home/runner/work/ezLibs/ezLibs/Tests/TestFile/CMakeLists.txt;0;")
add_test(TestEzFileWatcher_start_stop "/home/runner/work/ezLibs/ezLibs/_codeql_build_dir/Tests/TestFile/EzLibs_TestFile" "TestEzFileWatcher_start_stop")
set_tests_properties(TestEzFileWatcher_start_stop PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ezLibs/ezLibs/Tests/CMakeLists.txt;41;add_test;/home/runner/work/ezLibs/ezLibs/Tests/TestFile/CMakeLists.txt;85;AddTest;/home/runner/work/ezLibs/ezLibs/Tests/TestFile/CMakeLists.txt;0;")
add_test(TestEzFileWatcher_Dir "/home/runner/work/ezLibs/ezLibs/_codeql_build_dir/Tests/TestFile/EzLibs_TestFile" "TestEzFileWatcher_Dir")
set_tests_properties(TestEzFileWatcher_Dir PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ezLibs/ezLibs/Tests/CMakeLists.txt;41;add_test;/home/runner/work/ezLibs/ezLibs/Tests/TestFile/CMakeLists.txt;86;AddTest;/home/runner/work/ezLibs/ezLibs/Tests/TestFile/CMakeLists.txt;0;")
add_test(TestEzFileWatcher_File_PATH "/home/runner/work/ezLibs/ezLibs/_codeql_build_dir/Tests/TestFile/EzLibs_TestFile" "TestEzFileWatcher_File_PATH")
set_tests_properties(TestEzFileWatcher_File_PATH PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ezLibs/ezLibs/Tests/CMakeLists.txt;41;add_test;/home/runner/work/ezLibs/ezLibs/Tests/TestFile/CMakeLists.txt;87;AddTest;/home/runner/work/ezLibs/ezLibs/Tests/TestFile/CMakeLists.txt;0;")
add_test(TestEzFileWatcher_File_GLOB "/home/runner/work/ezLibs/ezLibs/_codeql_build_dir/Tests/TestFile/EzLibs_TestFile" "TestEzFileWatcher_File_GLOB")
set_tests_properties(TestEzFileWatcher_File_GLOB PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ezLibs/ezLibs/Tests/CMakeLists.txt;41;add_test;/home/runner/work/ezLibs/ezLibs/Tests/TestFile/CMakeLists.txt;88;AddTest;/home/runner/work/ezLibs/ezLibs/Tests/TestFile/CMakeLists.txt;0;")
add_test(TestEzFileWatcher_File_REGEX "/home/runner/work/ezLibs/ezLibs/_codeql_build_dir/Tests/TestFile/EzLibs_TestFile" "TestEzFileWatcher_File_REGEX")
set_tests_properties(TestEzFileWatcher_File_REGEX PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ezLibs/ezLibs/Tests/CMakeLists.txt;41;add_test;/home/runner/work/ezLibs/ezLibs/Tests/TestFile/CMakeLists.txt;89;AddTest;/home/runner/work/ezLibs/ezLibs/Tests/TestFile/CMakeLists.txt;0;")
add_test(TestEzVoxWriter_Writer "/home/runner/work/ezLibs/ezLibs/_codeql_build_dir/Tests/TestFile/EzLibs_TestFile" "TestEzVoxWriter_Writer")
set_tests_properties(TestEzVoxWriter_Writer PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ezLibs/ezLibs/Tests/CMakeLists.txt;41;add_test;/home/runner/work/ezLibs/ezLibs/Tests/TestFile/CMakeLists.txt;127;AddTest;/home/runner/work/ezLibs/ezLibs/Tests/TestFile/CMakeLists.txt;0;")
add_test(TestEzVdbWriter_Writer "/home/runner/work/ezLibs/ezLibs/_codeql_build_dir/Tests/TestFile/EzLibs_TestFile" "TestEzVdbWriter_Writer")
set_tests_properties(TestEzVdbWriter_Writer PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ezLibs/ezLibs/Tests/CMakeLists.txt;41;add_test;/home/runner/work/ezLibs/ezLibs/Tests/TestFile/CMakeLists.txt;133;AddTest;/home/runner/work/ezLibs/ezLibs/Tests/TestFile/CMakeLists.txt;0;")
