name: Win

on:
  push:
    branches:
    - master
    paths-ignore:
    - 'doc/**'
    - '.gitignore'
    - 'README.md'
    - 'LICENSE'

jobs:
  build_Win_latest:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: master
    - name: configure
      run: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DTESTING_EZ_EXPR=ON -DTESTING_EZ_GRAPH=ON -DTESTING_EZ_GRAPH=ON -DTESTING_EZ_TOOLS=ON
    - name: build
      run: cmake --build build
    - name: test
      run: ctest --output-on-failure
